services:
  db: 
    image: mongo
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  app:
    image: node:18
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - $APP_PORT:$APP_PORT
    env_file:
      - .env
    environment:
      - MONGO_HOST=db
      - APP_HOST=app
    command: npm run dev
    links:
      - db